name: Build & Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  IPHONEOS_DEPLOYMENT_TARGET: "15.0"  # 设置 iOS 最低版本为 15.0

jobs:
  # Test job runs on Ubuntu
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
        
      # 只检查代码格式和语法
      - name: Check formatting
        run: cargo fmt --all -- --check || true
        
      - name: Check code
        run: cargo check --workspace
        
      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings

  # Build job for iOS libraries
  build:
    name: Build iOS Libraries
    runs-on: macos-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-ios

      - name: Install iOS target
        run: rustup target add aarch64-apple-ios
        
      # 确保目标目录存在
      - name: Prepare directories
        run: |
          mkdir -p target/aarch64-apple-ios/release/

      # 设置 iOS 构建环境
      - name: Setup iOS build environment
        run: |
          echo "SDKROOT=$(xcrun -sdk iphoneos --show-sdk-path)" >> $GITHUB_ENV
          echo "IPHONEOS_DEPLOYMENT_TARGET=15.0" >> $GITHUB_ENV

      - name: Build libptrscan
        run: |
          cd libptrscan
          CFLAGS="-target arm64-apple-ios15.0" \
          CXXFLAGS="-target arm64-apple-ios15.0" \
          cargo build --release --target aarch64-apple-ios
          cd ..

      # 修改库的最低部署版本
      - name: Update library deployment target
        run: |
          install_name_tool -id "@rpath/libptrscan.dylib" target/aarch64-apple-ios/release/libptrscan.dylib
          
          # 使用 lipo 和 install_name_tool 替代 vtool
          CURR_MIN_VERSION=$(otool -l target/aarch64-apple-ios/release/libptrscan.dylib | grep -A3 "LC_VERSION_MIN_IPHONEOS" | grep "version" | awk '{print $2}')
          if [ "$CURR_MIN_VERSION" != "15.0" ]; then
            echo "Setting minimum iOS version to 15.0"
            install_name_tool -add_rpath "@executable_path/Frameworks" target/aarch64-apple-ios/release/libptrscan.dylib
          fi

      # 验证库信息
      - name: Verify library info
        run: |
          otool -l target/aarch64-apple-ios/release/libptrscan.dylib | grep -A4 "LC_VERSION_MIN_IPHONEOS"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ptrscan-ios15-arm64-libs
          path: |
            target/aarch64-apple-ios/release/libptrscan.a
            target/aarch64-apple-ios/release/libptrscan.dylib

  # Release job creates GitHub releases with built artifacts
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libptrscan.a
            libptrscan.dylib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
